### ISSUE TITLE
I think this is a bug?

### ISSUE THREAD

**Issue by woshihuo12** [hcyang1012/vscode_ctags#3]
public search(targetSymbol : string, error: (msg : string) => any ){ 
135         this._reset_if_need(); 
136         var fs = require("fs"); 
137  
138         if(file_manager.file_exists(this._get_tagpath())){ 
139             error("Cannot read ctag file. Please run CTAGS:Generate command first."); 
140         }else{ 
141             if(this._status != Status.LOADED){ 
142                 error("Loading tag info.. Please wait for a while and try again"); 
143                 this._load_tags(); 
144                 return; 
145             } else {  
146                 this._tag_search(targetSymbol);  
147             }  
148         } 
149     }   

this:
138         if(file_manager.file_exists(this._get_tagpath())){ 
139             error("Cannot read ctag file. Please run CTAGS:Generate command first."); 
140         }else{ 

if tag file exists, you tell can't read?????why?

**Comment by hcyang1012** [comment]
It seems you're right.
I will check and response it as soon as possible. 
Thanks.

**Comment by woshihuo12** [comment]
thanks...
and i want a other question:
when i use ext install ctags, where the ctags installed? i can't find it...
can u tell me?

**Comment by hcyang1012** [comment]
As mentioned in README file, this is the extension to use CTAG utility.
Therefore, you should download and install the ctag program. (http://ctags.sourceforge.net/) first, 
then add the installed directory to your 'PATH' environment variable.

**Comment by hcyang1012** [comment]
Bug fixed, applied to version 0.2.5.
Please refer the [commit](https://github.com/hcyang1012/vscode_ctags/commit/cc6353924655178e98523419f31196a024f12de3)
Issue close.

**Comment by lukeaus** [comment]
@hcyang1012  Can you push 0.2.5 to the vscode store...need to see if this helps with an issue I am having. Thanks

**Comment by hcyang1012** [comment]
@lukeaus I've published 0.2.5 just before. Thanks!

**Comment by lukeaus** [comment]
Thanks!
