### ISSUE TITLE
what's event-stream?

### ISSUE THREAD

**Issue by woshihuo12** [hcyang1012/vscode_ctags#4]
26 export function parse_file_line(file_path : string, parse : (line:string)=>void, error : () => void, success  : () => void){ 
27         let fs = require('fs') 
28         let es = require('event-stream'); 

line 28,  require('event-stream'); failure...the following code can't run...

**Comment by hcyang1012** [comment]
Please refer : [this site](https://github.com/dominictarr/event-stream)
Did you run 'npm install' command?

**Comment by woshihuo12** [comment]
how use vsc do command npm install??

**Comment by woshihuo12** [comment]
how use vsc do command npm install event-stream??

**Comment by hcyang1012** [comment]
On command line (e.g. linux or windows), just type below:
$ npm install //Thant's all.
Of course, you need to install nodejs and npm on your computer.

**Comment by woshihuo12** [comment]
ok, thank u i wil have a try.

**Comment by hcyang1012** [comment]
Good luck :+1:
